## Merge files on ST_CASE each year

In [8]:
import os
import pandas as pd
from functools import reduce

In [9]:
# Import previously cleaned files
# Accidents
accident_2018 = os.path.join("..", "Cleaned","Accident", "2018_Accident.csv")
accident_2017 = os.path.join("..", "Cleaned","Accident", "2017_Accident.csv")
accident_2016 = os.path.join("..", "Cleaned","Accident", "2016_Accident.csv")
accident_2015 = os.path.join("..", "Cleaned","Accident", "2015_Accident.csv")
accident_2014 = os.path.join("..", "Cleaned","Accident", "2014_Accident.csv")

# Person
person_2018 = os.path.join("..", "Cleaned","Person", "person_2018.csv")
person_2017 = os.path.join("..", "Cleaned","Person", "person_2017.csv")
person_2016 = os.path.join("..", "Cleaned","Person", "person_2016.csv")
person_2015 = os.path.join("..", "Cleaned","Person", "person_2015.csv")
person_2014 = os.path.join("..", "Cleaned","Person", "person_2014.csv")

# Vehicle
vehicle_2018 = os.path.join("..", "Cleaned","Vehicle", "2018_Vehicle.csv")
vehicle_2017 = os.path.join("..", "Cleaned","Vehicle", "2017_Vehicle.csv")
vehicle_2016 = os.path.join("..", "Cleaned","Vehicle", "2016_Vehicle.csv")
vehicle_2015 = os.path.join("..", "Cleaned","Vehicle", "2015_Vehicle.csv")
vehicle_2014 = os.path.join("..", "Cleaned","Vehicle", "2014_Vehicle.csv")

In [10]:
# Read imported files
# Accidents
accident_2018_df=pd.read_csv(accident_2018)
accident_2017_df=pd.read_csv(accident_2017)
accident_2016_df=pd.read_csv(accident_2016)
accident_2015_df=pd.read_csv(accident_2015)
accident_2014_df=pd.read_csv(accident_2014)

# Person
person_2018_df=pd.read_csv(person_2018)
person_2017_df=pd.read_csv(person_2017)
person_2016_df=pd.read_csv(person_2016)
person_2015_df=pd.read_csv(person_2015)
person_2014_df=pd.read_csv(person_2014)

# Vehicle
vehicle_2018_df=pd.read_csv(vehicle_2018)
vehicle_2017_df=pd.read_csv(vehicle_2017)
vehicle_2016_df=pd.read_csv(vehicle_2016)
vehicle_2015_df=pd.read_csv(vehicle_2015)
vehicle_2014_df=pd.read_csv(vehicle_2014)

## MERGE DFs

In [11]:
# Make an array of dfs
df_2018 = [accident_2018_df, person_2018_df, vehicle_2018_df]
df_2017 = [accident_2017_df, person_2017_df, vehicle_2017_df]
df_2016 = [accident_2016_df, person_2016_df, vehicle_2016_df]
df_2015 = [accident_2015_df, person_2015_df, vehicle_2015_df]
df_2014 = [accident_2014_df, person_2014_df, vehicle_2014_df]
# df_2013 = [accident_2013_df, person_2013_df, vehicle_2013_df]
# df_2012 = [accident_2012_df, person_2012_df, vehicle_2012_df]
# df_2011 = [accident_2011_df, person_2011_df, vehicle_2011_df]
# df_2010 = [accident_2010_df, person_2010_df, vehicle_2010_df]
# df_2009 = [accident_2009_df, person_2009_df, vehicle_2009_df]
# df_2008 = [accident_2008_df, person_2008_df, vehicle_2008_df]
# df_2007 = [accident_2007_df, person_2007_df, vehicle_2007_df]
# df_2006 = [accident_2006_df, person_2006_df, vehicle_2006_df]
# df_2005 = [accident_2005_df, person_2005_df, vehicle_2005_df]
# df_2004 = [accident_2004_df, person_2004_df, vehicle_2004_df]
# df_2003 = [accident_2003_df, person_2003_df, vehicle_2003_df]
# df_2002 = [accident_2002_df, person_2002_df, vehicle_2002_df]
# df_2001 = [accident_2001_df, person_2001_df, vehicle_2001_df]
# df_2000 = [accident_2000_df, person_2000_df, vehicle_2000_df]
# df_1999 = [accident_1999_df, person_1999_df, vehicle_1999_df]
# df_1998 = [accident_1998_df, person_1998_df, vehicle_1998_df]

In [12]:
# Merge the three data frames using the lambda function
df_2018_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2018)
df_2017_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2017)
df_2016_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2016)
df_2015_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2015)
df_2014_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2014)
# df_2013_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2013)
# df_2012_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2012)
# df_2011_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2011)
# df_2010_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2010)
# df_2009_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2009)
# df_2008_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2008)
# df_2007_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2007)
# df_2006_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2006)
# df_2005_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2005)
# df_2004_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2004)
# df_2003_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2003)
# df_2002_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2002)
# df_2001_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2001)
# df_2000_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_2000)
# df_1999_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_1999)
# df_1998_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ST_CASE'], how='inner'), df_1998)

In [13]:
df_2014_merged

,ST_CASE,PERSONS,COUNTY,CITY,DAY_x,MONTH_x,YEAR,DAY_WEEK,HOUR_x,MINUTE_x,...,L_STATE,PREV_ACC,PREV_DWI,PREV_SPD,VNUM_LAN,VSPD_LIM,ACC_TYPE,DEATHS,DR_DRINK,Year
0,480003,4,113,2590,1,1,2014,4,15,11,...,48,0,0,0,5,40,69,2,0,2014
1,480003,4,113,2590,1,1,2014,4,15,11,...,48,0,0,0,5,40,69,2,0,2014
2,480003,4,113,2590,1,1,2014,4,15,11,...,48,0,0,0,5,40,69,2,0,2014
3,480003,4,113,2590,1,1,2014,4,15,11,...,48,0,0,0,5,40,69,2,0,2014
4,480039,1,29,6090,5,1,2014,1,2,52,...,48,0,0,0,3,60,1,1,1,2014
5,480051,2,29,6090,8,1,2014,4,23,50,...,48,0,0,1,4,35,1,1,1,2014
6,480051,2,29,6090,8,1,2014,4,23,50,...,48,0,0,1,4,35,1,1,1,2014
7,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,24,2,1,2014
8,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,98,0,1,2014
9,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,24,2,1,2014
10,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,98,0,1,2014
11,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,24,2,1,2014
12,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,98,0,1,2014
13,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,24,2,1,2014
14,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,98,0,1,2014
15,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,24,2,1,2014
16,480076,5,201,3280,12,1,2014,1,20,44,...,48,0,0,0,3,45,98,0,1,2014
17,480077,2,405,0,12,1,2014,1,1,3,...,48,0,0,3,2,55,6,1,0,2014
18,480077,2,405,0,12,1,2014,1,1,3,...,48,0,0,3,2,55,6,1,0,2014
19,480091,2,157,6660,19,1,2014,1,2,0,...,48,0,0,0,4,65,25,1,1,2014
20,480091,2,157,6660,19,1,2014,1,2,0,...,48,0,0,0,4,65,25,1,1,2014
21,480107,2,201,3280,8,1,2014,4,15,40,...,48,0,0,0,2,45,46,1,0,2014
22,480107,2,201,3280,8,1,2014,4,15,40,...,48,0,0,0,2,45,46,1,0,2014
23,480117,1,91,0,11,1,2014,7,19,38,...,48,0,0,0,2,45,2,1,1,2014
24,480126,4,489,0,14,1,2014,3,12,50,...,95,99,99,99,2,65,98,1,0,2014
25,480126,4,489,0,14,1,2014,3,12,50,...,95,99,99,99,2,65,51,1,0,2014
26,480126,4,489,0,14,1,2014,3,12,50,...,95,99,99,99,2,65,98,1,0,2014
27,480126,4,489,0,14,1,2014,3,12,50,...,95,99,99,99,2,65,51,1,0,2014
28,480126,4,489,0,14,1,2014,3,12,50,...,95,99,99,99,2,65,98,1,0,2014
29,480126,4,489,0,14,1,2014,3,12,50,...,95,99,99,99,2,65,51,1,0,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,483190,1,167,2570,18,8,2014,2,3,53,...,48,0,0,0,5,35,11,1,1,2014
1000,483206,3,59,1400,17,8,2014,1,14,6,...,48,0,0,0,2,55,69,1,0,2014
1001,483206,3,59,1400,17,8,2014,1,14,6,...,48,0,0,0,2,55,69,1,0,2014
1002,483206,3,59,1400,17,8,2014,1,14,6,...,48,0,0,0,2,55,69,1,0,2014
1003,483213,3,27,4924,7,6,2014,7,2,14,...,48,1,0,1,2,75,52,1,1,2014
1004,483213,3,27,4924,7,6,2014,7,2,14,...,48,1,0,1,2,75,52,1,1,2014
1005,483213,3,27,4924,7,6,2014,7,2,14,...,48,1,0,1,2,75,52,1,1,2014
1006,483216,3,245,490,10,7,2014,5,23,53,...,48,99,99,99,3,55,83,1,1,2014
1007,483216,3,245,490,10,7,2014,5,23,53,...,48,99,99,99,3,55,83,1,1,2014
1008,483216,3,245,490,10,7,2014,5,23,53,...,48,99,99,99,3,55,83,1,1,2014
1009,483219,2,491,2380,29,7,2014,3,20,20,...,48,1,0,2,2,55,1,1,1,2014
1010,483219,2,491,2380,29,7,2014,3,20,20,...,48,1,0,2,2,55,1,1,1,2014
1011,483227,1,27,6810,29,11,2014,7,17,40,...,48,0,0,1,3,65,98,1,0,2014
1012,483228,1,309,7210,6,12,2014,7,5,45,...,48,0,0,0,2,40,1,1,1,2014
1013,483238,3,167,2570,22,2,2014,7,11,11,...,37,0,0,0,6,35,98,1,0,2014
1014,483238,3,167,2570,22,2,2014,7,11,11,...,37,0,0,0,6,35,98,1,0,2014
1015,483238,3,167,2570,22,2,2014,7,11,11,...,37,0,0,0,6,35,98,1,0,2014
1016,483239,2,85,4230,17,9,2014,4,13,41,...,48,1,0,0,4,45,86,1,0,2014
1017,483239,2,85,4230,17,9,2014,4,13,41,...,48,1,0,0,4,45,86,1,0,2014
1018,483251,4,141,2190,16,10,2014,5,16,29,...,24,0,0,0,3,45,69,1,0,2014
1019,483251,4,141,2190,16,10,2014,5,16,29,...,24,0,0,0,3,45,69,1,0,2014
1020,483251,4,141,2190,16,10,2014,5,16,29,...,24,0,0,0,3,45,69,1,0,2014
1021,483251,4,141,2190,16,10,2014,5,16,29,...,24,0,0,0,3,45,69,1,0,2014
1022,483254,2,375,150,10,8,2014,1,12,13,...,48,0,0,0,2,55,69,1,0,2014
1023,483254,2,375,150,10,8,2014,1,12,13,...,48,0,0,0,2,55,69,1,0,2014
1024,483255,4,209,3760,22,8,2014,6,20,56,...,48,0,0,0,3,70,0,1,0,2014
1025,483255,4,209,3760,22,8,2014,6,20,56,...,48,0,0,0,3,70,0,1,0,2014
1026,483255,4,209,3760,22,8,2014,6,20,56,...,48,0,0,0,3,70,0,1,0,2014
1027,483255,4,209,3760,22,8,2014,6,20,56,...,48,0,0,0,3,70,0,1,0,2014
1028,483261,1,439,2450,22,3,2014,7,0,15,...,48,0,0,0,2,35,11,1,1,2014

## Stack the merged dfs

In [14]:
stacked_df = pd.concat([df_2018_merged, df_2017_merged, df_2016_merged, df_2015_merged, df_2014_merged], axis=0, sort=False)

In [15]:
# display the stacked df to ensure everything looks correct
stacked_df

,ST_CASE,PERSONS,COUNTY,CITY,DAY_x,MONTH_x,YEAR,DAY_WEEK,HOUR_x,MINUTE_x,...,PREV_ACC,PREV_DWI,PREV_SPD,VNUM_LAN,VSPD_LIM,ACC_TYPE,DEATHS,DR_DRINK,Year,ROAD_FNC
0,480024,2,7,0,4,1,2018,5,18,6,...,0,0,3,2,55,69,1,0,2018,NaN
1,480024,2,7,0,4,1,2018,5,18,6,...,0,0,3,2,55,69,1,0,2018,NaN
2,480041,3,439,260,5,1,2018,6,20,35,...,0,0,0,2,40,69,1,0,2018,NaN
3,480041,3,439,260,5,1,2018,6,20,35,...,0,0,0,2,40,69,1,0,2018,NaN
4,480041,3,439,260,5,1,2018,6,20,35,...,0,0,0,2,40,69,1,0,2018,NaN
5,480044,2,27,3690,6,1,2018,7,20,8,...,0,0,0,3,35,24,1,1,2018,NaN
6,480044,2,27,3690,6,1,2018,7,20,8,...,0,0,1,3,35,25,0,0,2018,NaN
7,480044,2,27,3690,6,1,2018,7,20,8,...,0,0,0,3,35,24,1,1,2018,NaN
8,480044,2,27,3690,6,1,2018,7,20,8,...,0,0,1,3,35,25,0,0,2018,NaN
9,480052,2,439,2450,6,1,2018,7,18,8,...,0,0,1,8,40,98,1,0,2018,NaN
10,480052,2,439,2450,6,1,2018,7,18,8,...,0,0,1,8,40,98,1,0,2018,NaN
11,480058,2,201,3280,7,1,2018,1,16,18,...,2,0,2,3,40,45,1,0,2018,NaN
12,480058,2,201,3280,7,1,2018,1,16,18,...,2,0,2,3,40,45,1,0,2018,NaN
13,480077,1,21,0,9,1,2018,3,16,40,...,1,0,0,2,65,1,1,0,2018,NaN
14,480093,1,439,260,10,1,2018,4,1,5,...,1,0,0,3,45,7,1,0,2018,NaN
15,480094,1,439,2450,10,1,2018,4,13,37,...,0,0,1,2,40,2,1,0,2018,NaN
16,480103,1,29,6090,12,1,2018,6,1,23,...,0,0,0,2,45,13,0,0,2018,NaN
17,480103,1,29,6090,12,1,2018,6,1,23,...,0,0,0,2,45,13,0,0,2018,NaN
18,480108,1,201,3280,12,1,2018,6,19,55,...,1,0,1,2,65,6,1,0,2018,NaN
19,480132,4,209,0,15,1,2018,2,16,25,...,1,0,0,5,55,93,1,0,2018,NaN
20,480132,4,209,0,15,1,2018,2,16,25,...,1,0,0,5,55,93,1,0,2018,NaN
21,480132,4,209,0,15,1,2018,2,16,25,...,1,0,0,5,55,93,1,0,2018,NaN
22,480132,4,209,0,15,1,2018,2,16,25,...,1,0,0,5,55,93,1,0,2018,NaN
23,480152,1,303,4140,18,1,2018,5,19,41,...,2,0,2,7,40,13,0,1,2018,NaN
24,480152,1,303,4140,18,1,2018,5,19,41,...,2,0,2,7,40,13,0,1,2018,NaN
25,480167,3,135,0,20,1,2018,7,21,17,...,0,0,0,6,98,87,1,0,2018,NaN
26,480167,3,135,0,20,1,2018,7,21,17,...,0,0,0,6,98,87,1,0,2018,NaN
27,480167,3,135,0,20,1,2018,7,21,17,...,0,0,0,6,98,87,1,0,2018,NaN
28,480176,1,59,0,21,1,2018,1,22,5,...,0,0,0,2,75,0,1,0,2018,NaN
29,480180,1,201,3280,21,1,2018,1,17,9,...,0,0,0,2,35,6,1,1,2018,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,483190,1,167,2570,18,8,2014,2,3,53,...,0,0,0,5,35,11,1,1,2014,16.0
1000,483206,3,59,1400,17,8,2014,1,14,6,...,0,0,0,2,55,69,1,0,2014,1.0
1001,483206,3,59,1400,17,8,2014,1,14,6,...,0,0,0,2,55,69,1,0,2014,1.0
1002,483206,3,59,1400,17,8,2014,1,14,6,...,0,0,0,2,55,69,1,0,2014,1.0
1003,483213,3,27,4924,7,6,2014,7,2,14,...,1,0,1,2,75,52,1,1,2014,2.0
1004,483213,3,27,4924,7,6,2014,7,2,14,...,1,0,1,2,75,52,1,1,2014,2.0
1005,483213,3,27,4924,7,6,2014,7,2,14,...,1,0,1,2,75,52,1,1,2014,2.0
1006,483216,3,245,490,10,7,2014,5,23,53,...,99,99,99,3,55,83,1,1,2014,3.0
1007,483216,3,245,490,10,7,2014,5,23,53,...,99,99,99,3,55,83,1,1,2014,3.0
1008,483216,3,245,490,10,7,2014,5,23,53,...,99,99,99,3,55,83,1,1,2014,3.0
1009,483219,2,491,2380,29,7,2014,3,20,20,...,1,0,2,2,55,1,1,1,2014,5.0
1010,483219,2,491,2380,29,7,2014,3,20,20,...,1,0,2,2,55,1,1,1,2014,5.0
1011,483227,1,27,6810,29,11,2014,7,17,40,...,0,0,1,3,65,98,1,0,2014,1.0
1012,483228,1,309,7210,6,12,2014,7,5,45,...,0,0,0,2,40,1,1,1,2014,16.0
1013,483238,3,167,2570,22,2,2014,7,11,11,...,0,0,0,6,35,98,1,0,2014,3.0
1014,483238,3,167,2570,22,2,2014,7,11,11,...,0,0,0,6,35,98,1,0,2014,3.0
1015,483238,3,167,2570,22,2,2014,7,11,11,...,0,0,0,6,35,98,1,0,2014,3.0
1016,483239,2,85,4230,17,9,2014,4,13,41,...,1,0,0,4,45,86,1,0,2014,3.0
1017,483239,2,85,4230,17,9,2014,4,13,41,...,1,0,0,4,45,86,1,0,2014,3.0
1018,483251,4,141,2190,16,10,2014,5,16,29,...,0,0,0,3,45,69,1,0,2014,3.0
1019,483251,4,141,2190,16,10,2014,5,16,29,...,0,0,0,3,45,69,1,0,2014,3.0
1020,483251,4,141,2190,16,10,2014,5,16,29,...,0,0,0,3,45,69,1,0,2014,3.0
1021,483251,4,141,2190,16,10,2014,5,16,29,...,0,0,0,3,45,69,1,0,2014,3.0
1022,483254,2,375,150,10,8,2014,1,12,13,...,0,0,0,2,55,69,1,0,2014,4.0
1023,483254,2,375,150,10,8,2014,1,12,13,...,0,0,0,2,55,69,1,0,2014,4.0
1024,483255,4,209,3760,22,8,2014,6,20,56,...,0,0,0,3,70,0,1,0,2014,1.0
1025,483255,4,209,3760,22,8,2014,6,20,56,...,0,0,0,3,70,0,1,0,2014,1.0
1026,483255,4,209,3760,22,8,2014,6,20,56,...,0,0,0,3,70,0,1,0,2014,1.0
1027,483255,4,209,3760,22,8,2014,6,20,56,...,0,0,0,3,70,0,1,0,2014,1.0
1028,483261,1,439,2450,22,3,2014,7,0,15,...,0,0,0,2,35,11,1,1,2014,16.0

In [16]:
# write stacked df to csv file for machine learning model
stacked_df.to_csv('../Cleaned/2014_2018_merged.csv')

In [17]:
# write 2018 merged df to csv file for small batch machine learning model testing
df_2018_merged.to_csv('../Cleaned/2018_merged.csv')